package presentacion;

import datos.*;
import entidad.*;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DialogLibro extends javax.swing.JDialog {

    DefaultTableModel modeloLibro = new DefaultTableModel();
    DefaultTableModel modeloAutor = new DefaultTableModel();

    public DialogLibro() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        desHabilitar();
        String titulos[] = {"idautor", "nombre"};
        modeloAutor.setColumnIdentifiers(titulos);
        try {
            LibroDAO.getInstancia().mostrarLibros(modeloLibro);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void habilitar() {
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnConsultar.setEnabled(false);
    }

    public void desHabilitar() {
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }

    public void limpiarEntradas() {
        txtIdlibro.setText("");
        txtTitulo.setText("");
        txtIsbn.setText("");
        txtEditorial.setText("");
        txtPaginas.setText("");
        txtIdautor.setText("");
        txtNombre.setText("");
        String titulos[] = {"idautor", "nombre"};
        modeloAutor.setDataVector(null, titulos);
        txtIdlibro.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdlibro = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdautor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregarAutor = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarAutor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutor = new javax.swing.JTable();
        btnBuscarAutor = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIBROS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("idlibro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setText("titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("isbn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("editorial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setText("Paginas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        getContentPane().add(txtIdlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, -1));
        getContentPane().add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, -1));
        getContentPane().add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, -1));
        getContentPane().add(txtPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("autor"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("idautor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(txtIdautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        jLabel7.setText("nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

        btnAgregarAutor.setText("Agregar Autor");
        btnAgregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        btnEliminarAutor.setText("Eliminar Autor");
        btnEliminarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        tablaAutor.setModel(modeloAutor
        );
        jScrollPane1.setViewportView(tablaAutor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 130));

        btnBuscarAutor.setText("...");
        btnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 340, 260));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, 30));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, -1));

        jTable2.setModel(modeloLibro);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 630, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String idlibro = txtIdlibro.getText();
            String titulo = txtTitulo.getText();
            String isbn = txtIsbn.getText();
            String editorial = txtEditorial.getText();
            int paginas = Integer.parseInt(txtPaginas.getText());
            Libro libro = new Libro(idlibro, titulo, isbn, editorial, paginas);
            int nfilas = modeloAutor.getRowCount();

            for (int i = 0; i < nfilas; i++) {
                String idautor = modeloAutor.getValueAt(i, 0).toString();
                String nombre = modeloAutor.getValueAt(i, 1).toString();
                Autor autor = new Autor(idautor, nombre);
                DetalleLibro det = new DetalleLibro(autor);
                libro.registrarDetalleLibro(det);
            }
            LibroDAO.getInstancia().insertar(libro);
            LibroDAO.getInstancia().mostrarLibros(modeloLibro);
            JOptionPane.showMessageDialog(null, "Libro registrado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        limpiarEntradas();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        limpiarEntradas();
        desHabilitar();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String idlibro = txtIdlibro.getText();
        if (idlibro.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "POR FAVOR INGRESA idlibro");
        } else {
            try {
                Libro x = LibroDAO.getInstancia().buscarLibro(idlibro);
                if (x != null) {
                    txtIdlibro.setText(x.getIdlibro());
                    txtTitulo.setText(x.getTitulo());
                    txtIsbn.setText(x.getIsbn());
                    txtEditorial.setText(x.getEditorial());
                    txtPaginas.setText(String.valueOf(x.getPaginas()));
                    ListaDetalleLibro LD = x.getLD();
                    modeloAutor.getDataVector().removeAllElements();
                    for (int i = 0; i < LD.getN(); i++) {
                        DetalleLibro det = LD.getElemento(i);
                        String idautor = det.getAutor().getIdautor();
                        String nombre = det.getAutor().getNombre();
                        String fila[] = {idautor, nombre};
                        modeloAutor.addRow(fila);
                    }
                    habilitar();
                } else {
                    JOptionPane.showMessageDialog(null, "El idlibro no existe");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            String idlibro = txtIdlibro.getText();
            String titulo = txtTitulo.getText();
            String isbn = txtIsbn.getText();
            String editorial = txtEditorial.getText();
            int paginas = Integer.parseInt(txtPaginas.getText());
            Libro libro = new Libro(idlibro, titulo, isbn, editorial, paginas);
            int nfilas = modeloAutor.getRowCount();

            for (int i = 0; i < nfilas; i++) {
                String idautor = modeloAutor.getValueAt(i, 0).toString();
                String nombre = modeloAutor.getValueAt(i, 1).toString();
                Autor autor = new Autor(idautor, nombre);
                DetalleLibro det = new DetalleLibro(autor);
                libro.registrarDetalleLibro(det);
            }
            LibroDAO.getInstancia().actualizar(libro);
            LibroDAO.getInstancia().mostrarLibros(modeloLibro);
            JOptionPane.showMessageDialog(null, "Libro modificado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        limpiarEntradas();
        desHabilitar();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Deseas Eliminarlo ", "Eliminar Dato", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                String idautor = txtIdlibro.getText();
                LibroDAO.getInstancia().eliminar(idautor);
                JOptionPane.showMessageDialog(this, "Registro eliminado");
                LibroDAO.getInstancia().mostrarLibros(modeloLibro);
            } else {
                JOptionPane.showMessageDialog(null, "El idlibro no existe");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        limpiarEntradas();
        desHabilitar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        // TODO add your handling code here:
        DialogBuscarAutor f = new DialogBuscarAutor();
        f.setVisible(true);
        Autor autor = f.autorSelec;
        txtIdautor.setText(autor.getIdautor());
        txtNombre.setText(autor.getNombre());
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    private void btnAgregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAutorActionPerformed
        // TODO add your handling code here:
        String idautor = txtIdautor.getText();
        String nombre = txtNombre.getText();
        String fila[] = {idautor, nombre};

        modeloAutor.addRow(fila);
        txtIdautor.setText("");
        txtNombre.setText("");
        txtIdautor.requestFocus();
    }//GEN-LAST:event_btnAgregarAutorActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtIdautor.setText("");
        txtNombre.setText("");
        txtIdautor.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutorActionPerformed
        // TODO add your handling code here:
        int i = tablaAutor.getSelectedRow();
        if (i != -1) {
            int rpta = JOptionPane.showConfirmDialog(null, "Esta seguro?", "Eliminar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rpta == JOptionPane.OK_OPTION) {
                modeloAutor.removeRow(i);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un autor", "Eliminar", 1);
        }
    }//GEN-LAST:event_btnEliminarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLibro dialog = new DialogLibro();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarAutor;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarAutor;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tablaAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtIdautor;
    private javax.swing.JTextField txtIdlibro;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
